[graph]
# Cargo deny will check dependencies via `--all-features`
all-features = true

[sources]
unknown-registry = "deny"

[licenses]
version = 2
confidence-threshold = 1.0

# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
allow = [
    "0BSD",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "LicenseRef-ring",
    "MIT",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]

[[licenses.clarify]]
expression = "LicenseRef-ring"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"

[advisories]
ignore = [
    "RUSTSEC-2025-0056", # adler2 unmaintained (requires upstream updates) (2025-09-09)
    "RUSTSEC-2024-0421", # idna unmaintained (requires upstream updates) (2025-09-09)
]