name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2

      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # 2025-04-29
        with:
          toolchain: stable

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-features

      - name: Build
        run: |
          sudo apt-get install musl-tools # required for building ring
          cargo build --release --locked --target x86_64-unknown-linux-musl

  docker:
    name: Test Docker build
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1 https://github.com/docker/setup-buildx-action/releases/tag/v3.11.1

      - name: Build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0 https://github.com/docker/build-push-action/releases/tag/v6.18.0
        with:
          push: false
          load: true
          tags: world-id-bridge-ci:latest
          cache-from: type=gha
          cache-to: "type=gha,mode=max"
          platforms: linux/amd64

      - name: Run Docker container
        run: |
          docker run -d --network host --env-file .env.example --name world-id-bridge-ci-container world-id-bridge-ci:latest

          # Wait for the application to start
          sleep 10

          # Output logs to GitHub action
          docker logs world-id-bridge-ci-container

      - name: Health check Docker container
        run: curl -f http://0.0.0.0:8000/

      - name: Clean up
        run: |
          docker stop world-id-bridge-ci-container
          docker rm world-id-bridge-ci-container

  deny:
    name: Cargo deny
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2

      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # 2025-04-29
        with:
          toolchain: stable

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@30f817c6f72275c6d54dc744fbca09ebc958599f # v2.0.12 https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v2.0.12
        with:
          command: check
